### ISSUE TITLE
Slack と GitHub の連携

### ISSUE THREAD

**Issue by tsutaj** [hcpc-hokudai/hcpc-hokudai.github.io#5]
## 概要
ホームページの更新・機能追加に関する議論を (無料版の) Slack で行うと、以下の弊害が出る
- 話題ごとにまとまっていないので議論しづらい
- そのうち post が消える (というか見えなくなる) ので、過去の議論を見ようとしたときに困るときが出てくるはず

そのため、Slack ではなく GitHub の Issue を介してやり取りをすることが望ましく、GitHub での各 Action を Slack に通知する形を取りたい。

## 作業内容
- GitHub App を Slack と連携させる
  - `issues`, `pulls`, `commits` (`master` ブランチに対して), `comments` を有効化させた
  - それぞれがなにを意味するのかは [Slack の Help](https://github.com/integrations/slack#configuration) を参照
- うまくいっていればこの Issue が Slack に通知されるはず
  - Slack に表示されたことを確認できたら Close します

**Comment by rsk0315** [comment]
じー

**Comment by tsutaj** [comment]
Slack でも見えてるね 大丈夫そう

では Issue 閉じます
